export const ROUTES = {
  home: '/',
  aboutCompany: '/about-company',
  branches: '/branches',
  visionAndMessage: '/vision-and-message',
  organizationStructure: '/organization-structure',
  contractsRegulation: '/contracts-regulation',
  companyAchievements: '/company-achievements',
  adviceAndContact: '/advice-and-contact',
  cyberSecurityGuidelines: '/cyber-security-guidelines',
  forKidsAndWomen: '/for-kids-and-women',
  waterQuality: '/water-quality',
  refiningWater: '/refining-water',
  labOfCompanyWater: '/lab-of-company-water',
  labOfCompany: '/lab-of-company',
  wasteOfCompany: '/waste-of-company',
  trainingOfCompany: '/training-of-company',
  informationTechnologyOfCompany: '/information-technology-of-company',
  schoolSubmissionData: '/school-submission-data',
  schoolGallery: '/school-of-company',
  sportOfCompany: '/sport-of-company',
  sewageTreatment: '/sewage-treatment',
  safeSewageDisposal: '/safe-sewage-disposal',
  saveSewageNetwork: '/save-sewage-network',
  industrialWaste: '/industrial-waste',
  industrialWasteRole: '/industrial-waste-role',
  customerCharter: '/customer-charter',
  newsArchive: '/news-archive',
  newsDetails: '/news/:id',
  projectsArchive: '/projects-archive',
  projectDetails: '/projects/:id',
  tendersArchive: '/tenders-archive',
  tenderDetails: '/tenders/:id',
  generalAdminTraining: '/general-admin-training',
  callCenter: '/call-center',
  provideRequest: '/provide-request',
  provideComplaine: '/provide-complaine',
  hotlineApp: '/hotline-app',
  myReadingApp: '/my-reading-app',
  integritySupportOverview: '/nabza-an-daam-elnazaha',
  integritySupportHighlights: '/abrz-amaal-daam-elnazaha',
  professionalConduct: '/professional-conduct',
  bossTrips: '/trips-the-boss',
  jobsAndCompetition: '/jobs-and-competition',
  resultOfWorker: '/result-of-worker',
  servicesEvidance: '/services-evidance',
  contractOnService: '/contract-on-service',
  search: '/search',
} as const;

export const LEGACY_ROUTE_REDIRECTS: ReadonlyArray<{ from: string; to: string }> = [
  { from: '/about', to: ROUTES.aboutCompany },
  { from: '/an-elsherka', to: ROUTES.aboutCompany },
  { from: '/branch-of-company', to: ROUTES.branches },
  { from: '/contract-and-sell', to: ROUTES.contractsRegulation },
  { from: '/company-achivement', to: ROUTES.companyAchievements },
  { from: '/adviceAndContact', to: ROUTES.adviceAndContact },
  { from: '/forKidsAndWomen', to: ROUTES.forKidsAndWomen },
  { from: '/forKids', to: ROUTES.forKidsAndWomen },
  { from: '/toWomen', to: ROUTES.forKidsAndWomen },
  { from: '/Riddence-waste-water', to: ROUTES.safeSewageDisposal },
  { from: '/save-web-waste-water', to: ROUTES.saveSewageNetwork },
  { from: '/manufactring-waste', to: ROUTES.industrialWaste },
  { from: '/waste-water-in-manufactring', to: ROUTES.industrialWasteRole },
  { from: '/news-company', to: ROUTES.newsArchive },
  { from: '/projects-company', to: ROUTES.projectsArchive },
  { from: '/projects', to: ROUTES.projectsArchive },
  { from: '/allTenders', to: ROUTES.tendersArchive },
  { from: '/alltenders', to: ROUTES.tendersArchive },
  { from: '/hotline125', to: ROUTES.hotlineApp },
  { from: '/readme', to: ROUTES.myReadingApp },
  { from: '/traning-of-company', to: ROUTES.trainingOfCompany },
  { from: '/Customer-Charter', to: ROUTES.customerCharter },
  { from: '/result_of_worker', to: ROUTES.resultOfWorker },
  { from: '/Services-Evidance', to: ROUTES.servicesEvidance },
  { from: '/Contract-On-Service', to: ROUTES.contractOnService },
  { from: '/elslookElwazefy', to: ROUTES.professionalConduct },
] as const;


